language: generic

services:
  - docker

env:
  - DOCKER_COMPOSE_VERSION=1.29.2

before_install:
  - sudo rm /usr/local/bin/docker-compose
  - sudo curl -L "https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
  - sudo chmod +x /usr/local/bin/docker-compose
  - cat /home/travis/build/v-v-d/Async_API_sprint_1/.env.sample > /home/travis/build/v-v-d/Async_API_sprint_1/.env

jobs:
  include:
    - stage: tests
      name: "Unit Tests"
      script:
        - docker-compose -f docker-compose.test.yaml up --build --exit-code-from sut
