version: "3.8"

services:
  sut:
    container_name: api-tests
    build:
      context: .
      target: tests
    volumes:
      - ./src:/code
      - ./shared:/code/shared
      - ./shared/logs:/code/shared/logs
    env_file:
      - .env
    environment:
      - TESTING=True
